name: pulseaudio
summary: PulseAudio sound server
description: |
  PulseAudio, previously known as Polypaudio, is a sound server for POSIX and
  WIN32 systems. It is a drop in replacement for the ESD sound server with
  much better latency, mixing/re-sampling quality and overall architecture.

  Please find the source code for this snap at:
  https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/pulseaudio
grade: stable
confinement: strict
adopt-info: pulseaudio
base: core18

layout:
  /usr/share/applications:
    bind: $SNAP/usr/share/applications

environment:
  PATH:                      ${SNAP}/usr/sbin:${SNAP}/usr/bin:${SNAP}/sbin:${SNAP}/bin:${PATH}
  LD_LIBRARY_PATH:           ${LD_LIBRARY_PATH}:${SNAP}/usr/lib/pulseaudio:${SNAP}/usr/lib/pulse-11.1/modules/:${SNAP}/lib:${SNAP}/usr/lib:${SNAP}/lib/${SNAPCRAFT_ARCH_TRIPLET}:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
  PULSE_DLPATH:              ${SNAP}/usr/lib/pulse-11.1/modules
  PULSE_RUNTIME_PATH:        /var/run/pulse
  PULSE_SYSTEM:              1
  PULSE_STATE_PATH:          ${SNAP_DATA}/state
  # PULSE_SCRIPT this used to be default.pa, but docs say that is used only for user mode. we launchc in system mode
  # Note also that the script file to run is also set in the pulseaudio wrapper
  # It also seems that setting this var is not sufficient for pulse to run it, so the command arg is needed
  # and we could probably drop it from here
  PULSE_SCRIPT:              ${SNAP_DATA}/etc/pulse/system.pa
  PULSE_CONFIG:              ${SNAP_DATA}/etc/pulse/daemon.conf
  PULSE_CLIENTCONFIG:        ${SNAP_DATA}/etc/pulse/client.conf
  PULSE_CONFIG_PATH:         ${SNAP_DATA}/var/lib/pulse
  PULSE_ALSA_PATHS_DIR:      ${SNAP_DATA}/usr/share/pulseaudio/alsa-mixer
  ALSA_CONFIG_UCM:           ${SNAP_DATA}/usr/share/alsa/ucm
  ALSA_CONFIG_TPLG:          ${SNAP_DATA}/usr/share/alsa/topology
  ALSA_CONFIG_PATH:          ${SNAP_DATA}/usr/share/alsa/alsa.conf
  ALSA_MIXER_SIMPLE:         ${SNAP_DATA}/usr/share/alsa/smixer.conf
  ALSA_CONFIG_DIR:           ${SNAP_DATA}/usr/share/alsa/
  ALSA_CONFIG_UCM_VAR:       ${SNAP_DATA}/usr/share/alsa/ucm
  ALSA_CONFIG_TPLG_VAR:      ${SNAP_DATA}/usr/share/alsa/topology
  ALSA_PLUGIN_DIR:           ${SNAP}/usr/lib/alsa-lib
  ALSA_MIXER_SIMPLE_MODULES: ${SNAP}/usr/lib/alsa-lib/smixer
  ALSA_MIXER_SIMPLE_MPYTHON: ${SNAP}/usr/lib/alsa-lib/smixer/python/main.py

slots:
  audio-playback-service:
    interface: audio-playback

apps:
  pulseaudio:
    command: bin/pulseaudio
    daemon: simple
    slots:
      - audio-playback-service
    plugs: [ alsa ]
  alsamixer:
    command: usr/bin/alsamixer 
    plugs: [ audio-playback, network, alsa ]
  amixer:
    command: usr/bin/amixer 
    plugs: [ audio-playback, network, alsa ]
  aplay:
    command: usr/bin/aplay
    plugs: [ audio-playback, network, alsa ]
  pactl:
    command: bin/client-wrapper usr/bin/pactl
    plugs:
      - audio-playback
      - network
  paplay:
    command: bin/client-wrapper usr/bin/paplay
    plugs:
      - audio-playback
      - home
      - network
  parec:
    command: bin/client-wrapper usr/bin/parec
    plugs:
      - audio-playback
      - home
      - network
  config:
    command: bin/config

parts:
  glue:
    plugin: dump
    source: glue

  alsa-lib:
    plugin: autotools
    source: https://git.launchpad.net/ubuntu/+source/alsa-lib
    source-type: git
    source-branch: ubuntu/bionic
    override-pull: |
      snapcraftctl pull
      rm -rf manual
      [ -z "${SNAPCRAFT_PROJECT_DIR}" ] && SNAPCRAFT_PROJECT_DIR="../../.."
      quilt push -afq --leave-rejects --quiltrc=${SNAPCRAFT_PROJECT_DIR}/quiltrc
      git apply ${SNAPCRAFT_PROJECT_DIR}/alsa-lib-snap.patch
    configflags:
      - --prefix=/usr
      - --sysconfdir=/etc
      - --libexec=/usr/lib
      - --libdir=/usr/lib
      - --localstatedir=/var
      - --with-plugindir=/usr/lib/alsa-lib
      - --disable-silent-rules
      - --disable-static
      - --disable-python
    stage-packages:
      - alsa-utils

  pulseaudio:
    after:
      - alsa-lib
    plugin: autotools
    source: https://git.launchpad.net/ubuntu/+source/pulseaudio
    source-type: git
    source-branch: ubuntu/bionic
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags | cut -c 19-)
      rm -rf manual
      [ -z "${SNAPCRAFT_PROJECT_DIR}" ] && SNAPCRAFT_PROJECT_DIR="../../.."
      quilt push -afq --leave-rejects --quiltrc=../../../quiltrc
      git apply ${SNAPCRAFT_PROJECT_DIR}/pulseaudio-snap.patch
    build-packages:
      - intltool
      - libasound2-dev
      - libdbus-1-dev
      - libjson-c-dev
      - libglib2.0-dev
      - libspeexdsp-dev
      - libbluetooth-dev
      - libwebrtc-audio-processing-dev
      - libltdl-dev
      - libsndfile1-dev
      - libx11-xcb-dev
      - libx11-dev
      - libtdb-dev
      - libudev-dev
      - libasyncns-dev
      - libxcb1-dev
      - libsbc-dev
      - quilt
    configflags:
      - --prefix=/usr
      - --sysconfdir=/etc
      - --libexec=/usr/lib
      - --libdir=/usr/lib
      - --localstatedir=/var
      - --enable-udev
      - --disable-rpath
      - --disable-orc
      - --disable-gconf
      - --disable-bluez4
      - --disable-bluez5
      - --disable-esound
      - --disable-adrian-aec
      - --disable-gtk3
      - --disable-hal-compat
      - --disable-systemd-login
      - --without-caps
      - --disable-webrtc-aec
      - --disable-dbus
      - --disable-oss-output
      - --disable-oss-wrapper
      - --disable-jack
      - --disable-x11
      - --with-system-user=root
      - --with-system-group=root
    stage-packages:
      - libavahi-client3
      - libavahi-common3
      - libasyncns0
      - libflac8
      - libltdl7
      - libtdb1
      - libogg0
      - libsndfile1
      - libspeexdsp1
      - libvorbis0a
      - libvorbisenc2
      - libxcb1
      - liborc-0.4-0
      - libxdmcp6
      - libxau6
      - libsbc1
      - libx11-6
      - libx11-xcb1
      - jq
    stage:
      - etc
      - lib
      - usr/bin/pacat
      - usr/bin/pactl
      - usr/bin/paplay
      - usr/bin/parec
      - usr/bin/pulseaudio
      - usr/bin/jq
      - usr/lib
      - usr/share/pulseaudio
      - usr/bin/pacmd
      - -etc/pulse/system.pa
      - -etc/pulse/daemon.conf

  custom:
    after:
      - pulseaudio
    source: config
    plugin: dump

  libasound2:
    plugin: nil
    stage-packages:
      - libasound2
      - libasound2-plugin-smixer
    organize:
       usr/lib/*/alsa-lib/: usr/lib/
    stage:
      - usr/lib/alsa-lib
